import fs from 'fs';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import dotenv from 'dotenv';
dotenv.config();
import { account, book } from './db/schema.js';
import { SingleBar } from 'cli-progress';

const migrationsClient = postgres(process.env.SQL_CONNECTION_LINK || '', {
	max: 1,
});
const db = drizzle(migrationsClient);

let bar = new SingleBar({
	format: 'Migration | {bar} | {percentage}% | {value}/{total}',
	barCompleteChar: '\u2588',
	barIncompleteChar: '\u2591',
	hideCursor: true,
});

fs.readFile('./cz_all_authors/cz_all_authors.json', async (err, file) => {
	if (err) {
		console.log(err);
	}
	let data = JSON.parse(file);

	let total = data.length;
	bar.start(total, 0);
	let current = 0;

	for (const author of data) {
		bar.update(current++);
		if (!author.author) {
			continue;
		}
		if (!author.books) {
			continue;
		}
		const author_id = (
			await db
				.insert(account)
				.values({
					name: author.author,
					email: `czbooks${author.author}`,
					link_avatar: '',
					about_me: 'auto generated by system',
					system: true,
				})
				.onConflictDoNothing()
				.returning()
		)[0].id;
		for (const bookdata of author.books) {
			const book_id = (
				await db
					.insert(book)
					.values({
						author_id: author_id,
						title: bookdata.title,
						cover: bookdata.cover || '',
						description: bookdata.description || '',
						tags: bookdata.tags.map((e) => e.name) || [],
						cz_link: bookdata.link,
						published: true,
					})
					.returning()
			)[0].id;
			break;
		}
	}
	bar.stop();
	console.log('done');
	process.exit(0);
});
